name: Build and Publish Debian Package

on:
  push:
    branches:
      - master

jobs:
  build-deb:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y dpkg-dev wget

    - name: Build and install the .deb package
      run: |
        # Build the deb package
        sudo dpkg-deb -b kali-anonsurf-deb-src/ kali-anonsurf.deb
        # Install the .deb package
        sudo dpkg -i kali-anonsurf.deb || (sudo apt-get -f install && sudo dpkg -i kali-anonsurf.deb)

    - name: Get version from control file
      run: |
        VERSION=$(grep '^Version:' kali-anonsurf-deb-src/DEBIAN/control | cut -d' ' -f2)
        echo "VERSION=$VERSION" >> $GITHUB_ENV

    - name: Set up GitHub context
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh auth login --with-token <<< "$GITHUB_TOKEN"
        gh config set prompt disabled

    - name: Create and publish release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        VERSION="${{ env.VERSION }}"
        RELEASE_NAME="kali-anonsurf-$VERSION"
        TAG_NAME="v$VERSION"
        echo "Creating release: $RELEASE_NAME (tag: $TAG_NAME)"
        gh release create "$TAG_NAME" -t "$RELEASE_NAME" -n "Release for version $VERSION"

    - name: Upload .deb package to release
      uses: actions/upload-release-asset@v1.0.2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./kali-anonsurf.deb
        asset_name: kali-anonsurf-${{env.VERSION}}.deb
        asset_content_type: application/octet-stream
